### ISSUE TITLE
handwrittencharacters.mat Missing

### ISSUE THREAD

**Issue by bhargav191098** [artcogsys/ganrecon#1]
Hey there!
For training the alexnet for handwritten characters, the .mat is missing! Can the link be made available!

**Comment by kateiyas** [comment]
Hi! This is a public data set of handwritten characters - it is described in these papers and you need to grab it from Laurens van der Maaten ( https://lvdmaaten.github.io/publications/misc/characters.zip ): 

Schomaker, L. and Vuurpijl, L. (2000). Forensic writer identification: A benchmark data set 
and a comparison of two systems [internal report for the Netherlands Forensic Institute].

Van der Maaten, L. (2009). A new benchmark dataset for handwritten character recognition. 
Tilburg University.


I'll add the link to the comment, thanks for pointing it out!
